import { z } from "zod";
import { defineResource } from "@/builders";

const Address = z.object({ name: z.string().optional(), email: z.string() });

export const MessageSchema = z.object({
  id: z.string(),
  threadId: z.string(),
  connectionId: z.string(),
  tenantId: z.string().optional(),
  userId: z.string(),
  providerMessageId: z.string(),
  providerThreadId: z.string(),
  messageIdHeader: z.string().optional(),
  inReplyTo: z.string().optional(),
  references: z.array(z.string()).default([]),
  from: Address.optional(),
  to: z.array(Address).default([]),
  cc: z.array(Address).default([]),
  bcc: z.array(Address).default([]),
  replyTo: z.array(Address).default([]),
  subject: z.string().optional(),
  bodyText: z.string().optional(),
  bodyHtml: z.string().optional(),
  receivedAt: z.string(),
  sentAt: z.string().optional(),
  size: z.number().int().optional(),
  attachments: z.array(z.object({
    providerAttachmentId: z.string(),
    filename: z.string(),
    contentType: z.string(),
    size: z.number().int().default(0),
    cid: z.string().optional(),
    inline: z.boolean().default(false),
  })).default([]),
  labelIds: z.array(z.string()).default([]),
  folder: z.string().default("inbox"),
  isRead: z.boolean().default(false),
  isStarred: z.boolean().default(false),
  isOutgoing: z.boolean().optional(),
  wasEncrypted: z.boolean().optional(),
  signatureValid: z.boolean().optional(),
  trackerCount: z.number().int().optional(),
  unsubscribeMethods: z.object({ post: z.boolean().optional(), mailto: z.boolean().optional(), http: z.boolean().optional() }).optional(),
  icsEventId: z.string().optional(),
  toEmails: z.string().optional(),
  ccEmails: z.string().optional(),
  bccEmails: z.string().optional(),
  attachmentNames: z.string().optional(),
  headers: z.record(z.string()).optional(),
  preview: z.string().optional(),
  imageCount: z.number().int().optional(),
  linkCount: z.number().int().optional(),
  phishScore: z.number().optional(),
  indexedAt: z.string().optional(),
});

export const messageResource = defineResource({
  id: "mail.message",
  singular: "Message",
  plural: "Messages",
  schema: MessageSchema,
  displayField: "subject",
  searchable: ["subject", "bodyText"],
  icon: "Mail",
});
